#!/usr/bin/env bash
cp my_config_btstr /etc/nginx/sites-available/
cp 404.html /var/www/html/
rm /etc/nginx/sites-enabled/*
sudo ln -sf /etc/nginx/sites-available/my_config_btstr /etc/nginx/sites-enabled/
sudo service nginx restart
sudo service nginx status
